# Exports all armature actions/bones in the scene to player.anim.
import math
import sys
import bpy
from mathutils import Matrix

OUT = bpy.path.abspath("//player.anim")
ONCE = set() # Names of actions that should play once instead of looping

if "--" in sys.argv:
  bpy.ops.import_scene.gltf(filepath=sys.argv[sys.argv.index("--") + 1])

armatures = [o for o in bpy.data.objects if o.type == "ARMATURE"]
if len(armatures) != 1:
  raise Exception("expected exactly one armature, found %d" % len(armatures))

arm = armatures[0]
bones = arm.data.bones
pose = arm.pose.bones
scene = bpy.context.scene
fps = scene.render.fps / scene.render.fps_base

# Dynamically export ALL bones present in the armature
BONES = [b.name for b in bones]

# Model axes (x=side, y=up, z=forward)
if "arm_right" in bones and "arm_left" in bones and "head" in bones and "body" in bones:
  side = (bones["arm_right"].head_local - bones["arm_left"].head_local).normalized()
  up = bones["head"].head_local - bones["body"].head_local
  up = (up - side * up.dot(side)).normalized()
  forward = -side.cross(up)
  A = Matrix((side, up, forward))
else:
  A = Matrix.Identity(3)

rest = {n: bones[n].matrix_local.to_3x3().normalized() for n in BONES}
parent = {}
for n in BONES:
  p = pose[n].parent
  parent[n] = p.name if p is not None and p.name in BONES else None

anim_data = arm.animation_data_create()
original_action = anim_data.action

with open(OUT, "w") as f:
  f.write("# generated by export_anim.py\n")
  for action in bpy.data.actions:
    anim_data.action = action
    start, end = (int(round(x)) for x in action.frame_range)
    f.write("\nclip %s %s\n" % (action.name, "once" if action.name in ONCE else "loop"))

    rows = {n: [] for n in BONES}
    for frame in range(start, end + 1):
      scene.frame_set(frame)
      total = {n: pose[n].matrix.to_3x3().normalized() @ rest[n].inverted() for n in BONES}
      for n in BONES:
        delta = total[n] if parent[n] is None else total[parent[n]].inverted() @ total[n]
        e = (A @ delta @ A.transposed()).to_euler("YXZ")
        rows[n].append("%.4f %.3f %.3f %.3f" % ((frame - start) / fps, math.degrees(e.x), math.degrees(e.y), math.degrees(e.z)))


    for n in BONES:
      f.write("bone %s\n%s\n" % (n, "\n".join(rows[n])))



anim_data.action = original_action
print("wrote", OUT)
