# Exports the armature's skeleton and skinned meshes to player.skin (read by CustomModel.cs).
# Run it the same way as export_anim.py, on the same scene/armature.
#
# Requirements:
#   - exactly one armature; every bone is exported (names may contain spaces, not tabs)
#   - every mesh that uses the armature has an Armature modifier, no other modifiers (apply them first)
#   - a UV map, and bone weights on every vertex (vertex group name = bone name)
import sys
import bpy
from mathutils import Matrix

OUT = bpy.path.abspath("//player.skin")

if "--" in sys.argv:
  bpy.ops.import_scene.gltf(filepath=sys.argv[sys.argv.index("--") + 1])

armatures = [o for o in bpy.data.objects if o.type == "ARMATURE"]
if len(armatures) != 1:
  raise Exception("expected exactly one armature, found %d" % len(armatures))
arm = armatures[0]
bones = arm.data.bones

# KEEP IDENTICAL to the axes block in export_anim.py: positions must be in the same space as the
# animation deltas. "model" = derived from the rig, "blender" = raw armature space (CustomModel.cs
# converts that one to Unity axes on load).
if "arm_right" in bones and "arm_left" in bones and "head" in bones and "body" in bones:
  side = (bones["arm_right"].head_local - bones["arm_left"].head_local).normalized()
  up = bones["head"].head_local - bones["body"].head_local
  up = (up - side * up.dot(side)).normalized()
  forward = -side.cross(up)
  A = Matrix((side, up, forward))
  space = "model"
else:
  A = Matrix.Identity(3)
  space = "blender"

bone_index = {}
for i, b in enumerate(bones):
  if "\t" in b.name:
    raise Exception("bone name '%s' contains a tab" % b.name)
  bone_index[b.name] = i

meshes = []
for o in bpy.data.objects:
  if o.type == "MESH" and any(m.type == "ARMATURE" and m.object == arm for m in o.modifiers):
    for m in o.modifiers:
      if m.type != "ARMATURE":
        raise Exception("%s has a %s modifier; apply it first" % (o.name, m.type))
    meshes.append(o)
if not meshes:
  raise Exception("no mesh has an Armature modifier pointing at %s" % arm.name)


def influences(obj, vert, group_bone):
  ws = [(group_bone[g.group], g.weight) for g in vert.groups if g.group in group_bone and g.weight > 0]
  if not ws:
    raise Exception("vertex %d of %s has no bone weights" % (vert.index, obj.name))
  ws.sort(key=lambda t: -t[1])
  ws = ws[:4]
  total = sum(w for _, w in ws)
  ws = [(bone_index[name], w / total) for name, w in ws]
  return ws + [(0, 0.0)] * (4 - len(ws))


with open(OUT, "w") as f:
  f.write("# generated by export_model.py\n")
  f.write("space %s\n" % space)
  for b in bones:
    p = A @ b.head_local
    # tab separated so names can contain spaces
    f.write("bone\t%s\t%s\t%.6f\t%.6f\t%.6f\n" % (b.name, b.parent.name if b.parent else "-", p.x, p.y, p.z))

  base = 0
  for obj in meshes:
    mesh = obj.data
    mesh.calc_loop_triangles()
    uv_layer = mesh.uv_layers.active
    if uv_layer is None:
      raise Exception("%s has no UV map" % obj.name)
    group_bone = {g.index: g.name for g in obj.vertex_groups if g.name in bone_index}
    to_arm = arm.matrix_world.inverted() @ obj.matrix_world
    rot = to_arm.to_3x3()

    weights = {}  # blender vertex index -> influences
    written = {}  # (vertex, uv, flat normal) -> index in this file
    count = 0
    for tri in mesh.loop_triangles:
      poly = mesh.polygons[tri.polygon_index]
      ids = []
      for loop_index, vi in zip(tri.loops, tri.vertices):
        vert = mesh.vertices[vi]
        uv = uv_layer.data[loop_index].uv
        normal = vert.normal if poly.use_smooth else poly.normal
        key = (vi, round(uv.x, 5), round(uv.y, 5), None if poly.use_smooth else tuple(round(c, 4) for c in normal))
        if key not in written:
          if vi not in weights:
            weights[vi] = influences(obj, vert, group_bone)
          p = A @ (to_arm @ vert.co)
          n = (A @ (rot @ normal)).normalized()
          line = "v %.6f %.6f %.6f %.5f %.5f %.5f %.5f %.5f" % (p.x, p.y, p.z, n.x, n.y, n.z, uv.x, uv.y)
          for b, w in weights[vi]:
            line += " %d %.5f" % (b, w)
          f.write(line + "\n")
          written[key] = base + count
          count += 1
        ids.append(written[key])
      # blender's winding; CustomModel.cs reverses it because the mapping to Unity mirrors the mesh
      f.write("t %d %d %d\n" % tuple(ids))
    base += count

print("wrote", OUT, "space", space)
